"""Updated Enums name

Revision ID: 10
Revises: 9
Create Date: 2026-06-11 00:46:02.700626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "10"
down_revision: Union[str, Sequence[str], None] = "9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bookingstatusenum = postgresql.ENUM(
        "confirmed", "pending", "cancelled", name="bookingstatusenum"
    )
    roombathroomtypeenum = postgresql.ENUM(
        "shower", "bath", "jacuzzi", name="roombathroomtypeenum"
    )
    roomstatustypeenum = postgresql.ENUM(
        "available", "cleaning", "occupied", name="roomstatustypeenum"
    )
    userroleenum = postgresql.ENUM("user", "admin", name="userroleenum")

    bookingstatusenum.create(op.get_bind(), checkfirst=True)
    roombathroomtypeenum.create(op.get_bind(), checkfirst=True)
    roomstatustypeenum.create(op.get_bind(), checkfirst=True)
    userroleenum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "bookings",
        "status",
        existing_type=postgresql.ENUM(
            "confirmed", "pending", "cancelled", name="bookingstatus"
        ),
        type_=bookingstatusenum,
        existing_nullable=False,
        postgresql_using="status::text::bookingstatusenum",
    )
    op.alter_column(
        "room_types",
        "bathroom_type",
        existing_type=postgresql.ENUM(
            "shower", "bath", "jacuzzi", name="roombathroomtype"
        ),
        type_=roombathroomtypeenum,
        existing_nullable=False,
        postgresql_using="bathroom_type::text::roombathroomtypeenum",
    )
    op.alter_column(
        "rooms",
        "status",
        existing_type=postgresql.ENUM(
            "available", "cleaning", "occupied", name="roomstatustype"
        ),
        type_=roomstatustypeenum,
        existing_nullable=False,
        postgresql_using="status::text::roomstatustypeenum",
    )
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "admin", name="userrole"),
        type_=userroleenum,
        existing_nullable=False,
        postgresql_using="role::text::userroleenum",
    )

    op.execute("DROP TYPE IF EXISTS bookingstatus")
    op.execute("DROP TYPE IF EXISTS roombathroomtype")
    op.execute("DROP TYPE IF EXISTS roomstatustype")
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bookingstatus = postgresql.ENUM(
        "confirmed", "pending", "cancelled", name="bookingstatus"
    )
    roombathroomtype = postgresql.ENUM(
        "shower", "bath", "jacuzzi", name="roombathroomtype"
    )
    roomstatustype = postgresql.ENUM(
        "available", "cleaning", "occupied", name="roomstatustype"
    )
    userrole = postgresql.ENUM("user", "admin", name="userrole")

    bookingstatus.create(op.get_bind(), checkfirst=True)
    roombathroomtype.create(op.get_bind(), checkfirst=True)
    roomstatustype.create(op.get_bind(), checkfirst=True)
    userrole.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "admin", name="userroleenum"),
        type_=userrole,
        existing_nullable=False,
        postgresql_using="role::userrole",
    )
    op.alter_column(
        "rooms",
        "status",
        existing_type=postgresql.ENUM(
            "available", "cleaning", "occupied", name="roomstatustypeenum"
        ),
        type_=roomstatustype,
        existing_nullable=False,
        postgresql_using="status::roomstatustype",
    )
    op.alter_column(
        "room_types",
        "bathroom_type",
        existing_type=postgresql.ENUM(
            "shower", "bath", "jacuzzi", name="roombathroomtypeenum"
        ),
        type_=roombathroomtype,
        existing_nullable=False,
        postgresql_using="bathroom_type::roombathroomtype",
    )
    op.alter_column(
        "bookings",
        "status",
        existing_type=postgresql.ENUM(
            "confirmed", "pending", "cancelled", name="bookingstatusenum"
        ),
        type_=bookingstatus,
        existing_nullable=False,
        postgresql_using="status::bookingstatus",
    )

    op.execute("DROP TYPE IF EXISTS bookingstatusenum")
    op.execute("DROP TYPE IF EXISTS roombathroomtypeenum")
    op.execute("DROP TYPE IF EXISTS roomstatustypeenum")
    op.execute("DROP TYPE IF EXISTS userroleenum")
    # ### end Alembic commands ###
