"""Update Booking Model

Revision ID: 3
Revises: 2
Create Date: 2026-04-16 21:04:14.894585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3'
down_revision: Union[str, Sequence[str], None] = '2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_days', sa.Integer(), nullable=False))
    op.drop_column('bookings', 'total_price')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('bookings', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'total_days')
    # ### end Alembic commands ###
















