"""renamed colum in room_type like bathroom_type

Revision ID: 7
Revises: 6
Create Date: 2026-04-29 14:12:04.377552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7'
down_revision: Union[str, Sequence[str], None] = '6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('bathroom_type', sa.Enum('shower', 'bath', 'jacuzzi', name='roombathroomtype'), nullable=False))
    op.drop_column('room_types', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('role', postgresql.ENUM('shower', 'bath', 'jacuzzi', name='roombathroomtype'), autoincrement=False, nullable=False))
    op.drop_column('room_types', 'bathroom_type')
    # ### end Alembic commands ###
